name = "BoostingDecisionTrees"
uuid = "1d6c9a2e-c069-4b4d-9693-0e953be89117"
authors = ["Mateo Sakoman <mateo.sakoman@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
Random = "1.11.0"
StatsBase = "0.34.9"
julia = "1.11"
