name = "BoostingDecisionTrees"
uuid = "1d6c9a2e-c069-4b4d-9693-0e953be89117"
authors = ["Mateo Sakoman <mateo.sakoman@campus.tu-berlin.de>"]
version = "1.0.0-DEV"


[deps]
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
StatsBase = "0.34.9"
julia = "1.11"